<figure>
  <IMG src="figures/logo-esi-sba.png" WIDTH=300 height="100" ALIGN="right">
</figure>

# Practical Trainining Series on Software Engineering For Data Science  
*By Dr. Belkacem KHALDI (b.khaldi@esi-sba.dz)*

# Notebook 2: Getting Started with Python & Jupyter Notebook

The purpose of this [Jupyter Notebook] is to getting you started with Python and Jupyter. It provides a set of practical Training challenges that allow grasping the different concepts presented in the 2nd lecture.

## Section 1: Environment reproducibility for Python
Typical python projects use multiple packages for various tasks and some of the packages are shared between projects. However, sharing same packages between projects can cause problems. A virtual environment is a way to have multiple, parallel instances of the Python interpreter, each with different package sets and different configurations, avoiding the problems caused by sharing.

Some of the popular virtual environment implementations for Python are:

* Virtualenv
* Conda
* pipenv
* venv
In this Notebook, you will learn how to add a Conda virtual environment to your Jupyter Notebook.

### Manipulate Conda Commands:
Access to your Anaconda Powershell Terminal As Follows.
<figure>
  <IMG src="figures/snapshot-1-.png"  ALIGN="center">
</figure>

In the terminal, follow the steps below to get hans-on-experience using conda evironment:

  1. Navigate to your `Desktop` Folder as example
  2. Create a new Folder named `seds-lab2` by using window/Linux Command `mkdir` or `mk` based on your OS system.
  3. Navigate to your new created directory.
  4. Tape `python --version` to know your current python version used in your <base> enviironment.
  5. Create a new conda environment with the same name of your folder project siffixed by `-env`  by taping the following command:
    `conda create --name seds-lab2-env python=3.8`
 
    Note that with this command, we explicitly targetting the python version 3.8 to be installed in our environment. 
 
    <figure>
  <IMG src="figures/snapshot-2-.png"  ALIGN="center">
</figure> 
     
   Alternatively, you may create an environment with a specific version of Python and multiple packages as follows:
     `conda create -n <env-name> python=3.9 scipy=0.17.3 matplotlib`
     
  6. Verify that the new environment was installed correctly with the following conda command:
     `conda env list`
     
 If every thing goes correct, you should see your conda environment is listed. However, It is still not activated.
   <figure>
  <IMG src="figures/snapshot-3-.png"  ALIGN="center">
</figure>
     
  7. To activate it just tape the following command: `conda activate seds-lab2-env`
       
        <figure>
  <IMG src="figures/snapshot-4-.png"  ALIGN="center">
</figure>
  
  8. Install now the IPython kernel. Note that The IPython kernel is the Python execution backend for Jupyter Notebook. We will Install it in the newly-created virtual environment via the command below: `conda install ipykernel -y`. The `-y` option is just to prevent asking for confirmatioin.
            
      <figure>
  <IMG src="figures/snapshot-5-.png"  ALIGN="center">
</figure>       
   
  9. Now to list all the packages already installed in your current activated environement using the command : `conda list`.
          
 <figure>
  <IMG src="figures/snapshot-6-.png"  ALIGN="center">
</figure>  
     
  10. To return to your base conda env, just tape `conda deactivate`.
     
 <figure>
  <IMG src="figures/snapshot-7-.png"  ALIGN="center">
</figure> 
     
  11.  To difinitely delete your environement including all installed packages tape:  `conda remove --name seds-lab2-env --all` then confirm.
     
    <figure>
  <IMG src="figures/snapshot-8-.png"  ALIGN="center">
</figure>   
     

### Challenge 01:

Following the steps above:
1. set up a new virtual environment using conda with the latest python version as well as the following  packages: numpy, pandas, matplotlib, and scikit-learn with a single conda command.

2. Verify that your environment is correctly setup by listing it.

3. Finally delete definetely your environment.



## Section 2: Python Basics
### Basic Variable Types

`my_integer = 3.1428571  
_my_float = 3.1428571     
__my_float__ = 3.1428571  
€value = 42.95  
cost_in_€ = 42.95
cost_in_dollars = 42.95  
42.95 = cost_in_dollars  
dollar.price = 42.95  
favourite#tag = '#like4like'
favourite_hashtag = '#일상'
my_twit = """If you really want to write paragraphs,
and paragraphs of text, you do it with the triple quotes. Try it"""
x = y = z = 1
a, b, c = 1, 2, 3        
i, f, s = 42, 12.94, 'spam'
from = 'my friends'
raise = 'your glass'
pass = 'you shall not'
fail = 'you will not'
True = 'not False'
pay day = 'Thursday'
NA = 'not applicable' 
a = 42;                 
A = 13`     

* Test each of the above code  by executing ligne by Line (Copy and Past, then execute in a the cell below)
* Define whenever it is possible the type of your variable by taping `type(<variable_name>)` 
* What's the most interesting idea/concept you learned from this?

### Solution

* 1- Variable name does not define variable type
* 2- Variables can start with '_'
* 3- Variables can contain more than on of '_'
* 4- SyntaxError: invalid character '€'
* 5- SyntaxError: invalid character '€'
* 6- executed
* 7- SyntaxError: cannot assign to literal here
* 8- NameError: name 'dollar' is not defined (because dollar must be a defined object)
* 9- NameError: name 'favourite' is not defined (the hashtag comments the code)
* 10- executed
* 11- executed
* 12- executed
* 13- executed
* 14- executed
* 15- SyntaxError: invalid syntax (Python Keywords)
* 16- SyntaxError: invalid syntax (no space in variables)
* 17- executed
* 18- executed (we can write instructions with or without semicolons)

### Calculations with variables
Lets now perform some calculations with variables.

The standard expressions exist in Python:

| Operation      | Symbol |
|----------------|--------|
| Addition       | +      |
| Subtraction    | -      |
| Multiplication | *      |
| Division       | /      |
| Power of       | **     |
| Modulo         | %      | 


Given the above, use Python to solve the following problem:

The distance $d$ travelled by an object falling for time $t$, given in seconds, is $$d=\frac  {1}{2}gt^{2}$$ where $g$ is the gravitational constant = $9.8\, \text{m.s}^{-2}$. Calculate the distance that you will travel in free-fall gravity in 10 seconds:

```python
t = ____ # seconds
d = ____ # meters
print('The distance fallen is ' + str(d) + ' meters.')
```

### Solution

In [34]:
g = 9.8
t = 10

d = 0.5 * g * (t**2)
print('The distance fallen is ' + str(d) + ' meters.')

The distance fallen is 490.00000000000006 meters.


Try it now the other way around to determin the time taken for an object to fall that is:
$$ t= \sqrt  {\frac  {2d}{g}}$$

We will introduce the ``sqrt`` function later, but you can also calculate square root using a power of 0.5, as in $\sqrt{x} = x^{0.5}$.

Using that knowledge, how long will it take for an object to fall from the top of the building you are currently in:

```python
# Creates a string value in variable 'd'. Verify that it is a string type.
d = input('The height of the building, in meters, which I am currently in is: ')  
d = float(d)  # convert the string variable to a floating point value
t = ____ # seconds

# You might also want to investigate the "round" function at this point
# to improve the output for variable t.

print('The time for an object to fall from a building',
      'of ' + str(d) + ' meters tall is ' + str(t) + \
      ' seconds.')
```

### Solution

In [10]:
d = input('The height of the building, in meters, which I am currently in is: ') 
print(f'The type of the input d is: {type(d)}')

d = float(d)
g = 9.8

t = (( 2 * d ) / g ) ** 0.5
print('The time for an object to fall from a building',
      'of ' + str(d) + ' meters tall is ' + str(round(t,2)) + \
      ' seconds.')

The height of the building, in meters, which I am currently in is: 50
The type of the input d is: <class 'str'>
The time for an object to fall from a building of 50.0 meters tall is 3.19 seconds.


### Conditional Statments
Lets now perform some Conditional Operators with variables.

Some of the standard Conditional Operatore exist in Python:

| Operation      | Symbol |
|----------------|--------|
| Equal          | ==     |
| Not Equal      | !=     |
| Greater Than   | >      |
| less Than      | <      |
| ........       | ..     |



In the quadratic equation $$ax^2 + bx + c=0$$ the short-cut solution is given by $$ x= -\frac{b}{2a}$$
but only if $b^2 - 4ac=0$ and $a \neq 0$.

Verify if you can use this short-cut solution for these combinations:

* ``a=3, b=-1, c=2    # use tuple-assignment to create these 3 variables in 1 line of code``
* ``a=0, b=-1, c=2``  
* ``a=3, b=6, c=3``  

Write the Python code that will return ``True`` if you can use the shortcut, or ``False`` if you cannot.

### Solution

In [24]:
a, b, c = 3, 6, 3

Delta = b ** 2 - 4 * a * c

if (Delta == 0 and a !=0): print(True)
else: print(False)

True


### Built-in constants and mathematical functions

You will certainly need to calculate logs, exponentials, square roots, or require the value of $e$ or $\pi$ at some point.

In this last section we get a bit ahead, and load a Python library to provide this for us. Libraries - we will see later - are a collection of functions and variables that pre-package useful tools. Libraries can be large collections of code, and are for special purposes, so they are not loaded automatically when you launch Python.


In Python, there are several libraries that come standard, and one is the ``math`` library. Use the ``import`` command to load the library. The ``math`` library can be used as follows:

```python
import math
radius = 3 # cm
area_of_circle = math.pi * radius**2
print('The area of the circle is ' + str(area_of_circle))
```

Now that you know how to use the ``math`` library, it is worth searching what else is in it:

> https://www.google.com/search?q=python+math+library

All built-in Python libraries are documented in the same way. Searching this way usually brings up the link near the top. Make sure you look at the documentation for Python version 3.x.

Now that you have the documentation ready, use functions from that library to calculate:

* the *ceiling* and the *floor* of a number, for example ``a = 3.7``
* the log to the base $e$ of ``d = 100``
* the log to the base 10 of ``e = 100``
* the Golden ratio ${\dfrac {1+{\sqrt {5}}}{2}}$ 
* the factorial n=9, in other words $n!$
* check that  $n! \approx \sqrt{2\pi n} \cdot n^n e^{-n}$ 

### Solution

In [50]:
import math

a = 3.7
print(f'Ceiling of a: {math.ceil(a)}, floor of a: {math.floor(a)}')
print(f'The log to the base 𝑒 of 100: {math.log(100, math.e)}')
print(f'The log to the base 10 of 100: {math.log(100, 10)}')
print(f'The golden ratio: {(1 + math.sqrt(5))/2}')
n = 9
print(f'The factorial of n=9: {math.factorial(n)}')
print(f'with n=9 we have: n! = {math.factorial(n)}, so n ≈ {math.sqrt(2 * math.pi * n) * (n ** n) * (math.e ** -n)}')

Ceiling of a: 4, floor of a: 3
The log to the base 𝑒 of 100: 4.605170185988092
The log to the base 10 of 100: 2.0
The golden ratio: 1.618033988749895
The factorial of n=9: 362880
with n=9 we have: n! = 362880, so n ≈ 359536.8728419484


### Challenge
1. The population of a country could be approximated by the formula $$ p(t) = \dfrac{197 273 000}{1 + e^{− 0.03134(t − 1913)}}$$
where the time $t$ is in years.

 * What is the population in 1913?
 * What is the population in 2013?
 * Does the population grow and grow without bounds, or does it reach steady state (it stabilizes at some constant value eventually)
  
1. Explain to your partner whom you are working with, what some of the benefits are of writing your code in Python files.


### Solution

In [52]:
def population(t):
    return (197273000 / (1 + math.exp(-0.03134 * (t - 1913))))

print(f'The population in 1913 was: {round(population(1913))}')
print(f'The population in 2013 was: {round(population(2013))}')

The population in 1913 was: 98636500
The population in 2013 was: 189041513


### More about Strings
Lets create this string in Python:

```python
s = """In 1962, John Tukey described a field he called "data analysis", which resembles modern data science. In 1985, in a lecture given to the Chinese Academy of Sciences in Beijing, C. F. Jeff Wu used the term "data science" for the first time as an alternative name for statistics. Later, attendees at a 1992 statistics symposium at the University of Montpellier II acknowledged the emergence of a new discipline focused on data of various origins and forms, combining established concepts and principles of statistics and data analysis with computing."""
```

Now use the above string to perform the following actions. Look up the Standard library help files for strings (like we showed last time) to find the methods required.

1. Print it to screen completely in upper case.
2. Try the following: print(s * 8).
3. Try the following: print(s + s). Do these two mathematical operations make sense for strings?
4. What is the length of this string?
5. How many times does the word "the" appear in the string?
6. At which position in the string does the word `data science` appear? 
7. Return a boolean True or False if the string `statistics` is followed by a full stop.
8. Replace the instance of 'discipline' with 'field'.
9. Replace every space in the above sentence with a newline character, and reprint the sentence to the screen.

`Hint:`

The above are all effectively done using what are called methods.

A method an attribute of an object.

In the above, a string is your object and objects have one or more methods. You can get a list  of all metthods using the `dir(...)` command.

```python
dir(s)
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', 
'__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__',
'__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', 
'__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', 
'__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 
'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 
'format_map', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'isidentifier', 
'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 
'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 
'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 
'swapcase', 'title', 'translate', 'upper', 'zfill']
```

### Solution

In [22]:
### s = """In 1962, John Tukey described a field he called "data analysis", which resembles modern data science. In 1985, in a lecture given to the Chinese Academy of Sciences in Beijing, C. F. Jeff Wu used the term "data science" for the first time as an alternative name for statistics. Later, attendees at a 1992 statistics symposium at the University of Montpellier II acknowledged the emergence of a new discipline focused on data of various origins and forms, combining established concepts and principles of statistics and data analysis with computing."""
#print(s.upper())
#print(s * 8)
#print(s + s) 
#print(len(s))
#print(s.count('the'))
print(s.index('data science'))

word = 'statistics'
if(s[s.index(word)+ len(word)] == '.'):
    print('True')
else:
    print('False')

# print(s.replace('discipline', 'field'))
# print(s.replace(' ', '\n'))

88
True


### Compound Data Types: Lists

We will cover creating, adding, accessing and using lists of objects.

You have seen this before: create a list with the square bracket characters: ``[`` and ``]``.

For example: ``words = ['4th', 'year', 'students','are','very', 'excited','for','seds' ]``

One of the most useful functions in Python is ``len(...)``. Verify length of your list. Does it have the **type** you expect?

### Solution

In [101]:
words = ['4th', 'year', 'students','are','very', 'excited','for','seds' ]
print(f'return type of the function len is: {type(len(words))}')

return type of the function len is: <class 'int'>


The entries in the list can be mixed types (contrast this to most other programming languages!)
    
```python
group = ['pytorch', 'tesorflow', 100, 'machine learning' ]
```

An important test is to check if the list contains something:

```python
'tesorflow' in group
499 in group
```

Like we saw with strings, you can use the ``*`` and ``+`` operators:

```python
group * 3
group + group   # might not do what you expect!
group - group   # oooops
```

And like strings, you refer to them based on the position counter of 0:
```python
group[0]

# but this is also possible:
group[-3]

# however, is this expected?
group[4]
```

Accessing List items by Loop:
```python
for _it in group:
    print(_it)
```

### Solution

In [112]:
group = ['pytorch', 'tesorflow', 100, 'machine learning' ]

print('tesorflow' in group)
print(499 in group)
print(group * 3)
print(group + group)
# print(group - group ) (unsupported operand type(s) for -)

print(group[0])
print(group[-3])
# print(group[4]) (list index out of range)

for _it in group:
    print(_it)

True
False
['pytorch', 'tesorflow', 100, 'machine learning', 'pytorch', 'tesorflow', 100, 'machine learning', 'pytorch', 'tesorflow', 100, 'machine learning']
['pytorch', 'tesorflow', 100, 'machine learning', 'pytorch', 'tesorflow', 100, 'machine learning']
pytorch
tesorflow
pytorch
tesorflow
100
machine learning


Lists, also have  some methods that you can use. Lists in fact have far fewer methods than strings.
```python
dir(....) # what do you fill in here?
```

How many methods do you see which you can apply to a list? 

Let's try a few of them out:
1. Try ``append`` a new entry to the ``group`` list you created above: add the entry "fastai"
1. Create a new list ``reptiles = ['crocodile', 'turtle']`` and then try: ``group.extend(reptiles)``.
1. Print the list. Remove the ``crocodile`` and ``turtle`` entries from the list. Print it again to verify it succeeded. 
1. Use the following command: ``group.reverse()``, and print the ``group`` variable to the screen.
1. Try ``group.sort()`` and try fix the error message.


### Solution

In [127]:
group = ['pytorch', 'tesorflow', 100, 'machine learning' ]
reptiles = ['crocodile', 'turtle']

# dir(group)

group.append('fastai')

group.extend(reptiles)
print(f'extended list: {group}')

group.remove('crocodile')
group.remove('turtle')
print(f'original list: {group}')

group.reverse()
print(f'reversed list: {group}')

group[group.index(100)] = '100'
group.sort()
print(f'sorted list: {group}')

extended list: ['pytorch', 'tesorflow', 100, 'machine learning', 'fastai', 'crocodile', 'turtle']
original list: ['pytorch', 'tesorflow', 100, 'machine learning', 'fastai']
reversed list: ['fastai', 'machine learning', 100, 'tesorflow', 'pytorch']
sorted list: ['100', 'fastai', 'machine learning', 'pytorch', 'tesorflow']


#### More About Lists Indexing and Slicing
List are like strings, they can be indexed and sliced. For example lets create a list called `my_list` as follows:

```python
my_list = [_ for _ in 'abcdefghi']
my_list
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
```

##### Indexing
To retrieve an element of the list, we use the index operator (`[]`). Note that:
* Lists are “zero indexed”.
* It is possible to use negative indexing (from the end of the list), where `[-1]` returns the last element. 

```python
  0    1    2    3    4    5    6    7    8
  ↓    ↓    ↓    ↓    ↓    ↓    ↓    ↓    ↓
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
  ↑    ↑    ↑    ↑    ↑    ↑    ↑    ↑    ↑
 -9   -8   -7   -6   -5   -4   -3   -2   -1
```

##### Slicing
A slice is a subset of list elements. In the case of lists, a single slice will always be of contiguous elements. Slice notation takes the form
`
my_list[start:stop]
`
where `start` is the index of the first element to include, and `stop` is the index of the item to stop at without including it in the slice. So `my_list[1:5]` returns `['b', 'c', 'd', 'e']`

```python
  0    1    2    3    4    5    6    7    8
  ×    ↓    ↓    ↓    ↓    ×    ×    ×    ×
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
```

##### Stepping
The slicer can take an optional third argument, which sets the interval at which elements are included in the slice. So `my_list[::2]` returns `['a', 'c', 'e', 'g', 'i']`
```python
  0    1    2    3    4    5    6    7    8
  ↓    ×   ↓²    ×    ↓²   ×   ↓²    ×    ↓²
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
```

Try it: Given the string :
 ```python 
'I am very excited of pursuing the IASD specialization at ESI-SBA'.
```

- Outputs the reverse of the string using string slicing.
- Extract Every Even character and concatenate them to form a new string.

### Solution

In [148]:
s = 'I am very excited of pursuing the IASD specialization at ESI-SBA'

print(s[::-1])

print(s[1::2])

ABS-ISE ta noitazilaiceps DSAI eht gniusrup fo deticxe yrev ma I
 mvr xie fprun h ADseilzto tEISA


###  Compound Data Types: ``Dictionary`` data type

A dictionary is a Python ***object*** that is a flexible data container for other objects. It contains these objects using what are called ***key*** - ***value*** pairs. You create a dictionary like this:

```python
random_objects = {'an int': 45,
                  'a float': 12.34,
                  'short_list': [1, 4, 7],
                  'longer list': [2, 4, 6, 9, 12, 16, 20, 25, 30, 36, 42],
                  'website': "https://learnche.org",
                  'nested_tuple': (1, 2.0, [3, 4], '5', (6, 7.0))
                 }
print(random_objects)
```

Notice that it is unlikely when you print the ``random_objects`` variable, that you see the dictionary written back in the order shown above. Dictionaries are an ***unordered*** container. 

The ***keys*** and ***values*** of this dictionary are:
```python

# These both return a list:
random_objects.keys()
random_objects.values()

# What is the "type" of this dictionary?
print('The object is of: {}'.format(type(random_objects)))

# You can access individual elements:
random_objects['short_list']
```

In the above example, the keys were all ***string*** objects. But that is not required. You can use integers, floating point values, strings, tuples, or a mixture of them. There are other options too, but these are comprehensive enough.

Dictionary values may be any ***objects***, even other dictionaries. Yes, so a dictionary within a dictionary is possible. We will use this below. That is why we partially why we waited to introduce dictionaries until now.

Dictionary objects are excellent ***containers***. If you need to return several objects from a function, collect them in a dictionary, and return them in that single object. It is not required, but it can make your code neater, and more logical.

### Try it

Create a dictionary for yourself with 5 `key`-`value` pairs, which summarizes a regression model. The `key` is the first item below, followed by a description of what you should create as the `value`:
1. `intercept`: containing a floating-point value which is the intercept of your linear model
2. `slope`: a floating-point slope value
3. `R2`: the $R^2$ value of the regression model
4. `std_err`: a value which is the model's standard error

`Hint:`

we will just use the following code without deving into details to help return the results of your regression model using stats module from scipy package.

```python
from scipy import stats
slope, intercept, r2, _, std_err = stats.linregress(x, y)
```
Where x and y are two vectors (lists) of 5 floats each

You can create the above dictionary in a single line of code. But what if you want to add something new to an existing dictionary later?

```python
d = { ... } # create your dictionary
d['new key'] = 'additional value'
```

And you can overwrite an existing key-value pair in the same way:
```python
random_objects['an int'] = 'replaced with a string!'
```
This implies you can never have 2 keys which are the same. If you try to create a second key which already exists, it will overwrite the value associated with the existing key.

### Solution

In [13]:
from scipy import stats


x= [2.3, 4.5,4.6, 8.6, 4.5]
y= [8.3, 4.5,3.6, 9.0, 2.1]
slope, intercept, r2, _, std_err = stats.linregress(x, y)


dictionary = {
    'intercept' : intercept,
    'slope' : slope,
    'r2' : r2,
    'std_err' : std_err
}
dictionary['_'] = _
print(dictionary)

{'intercept': 3.620805369127518, 'slope': 0.38350910834132296, 'r2': 0.2908833981449312, 'std_err': 0.7282801194998828, '_': 0.6349270815571142}


## Section 3: Basic Notions of Vectors, Matrices and Arrays, without using Numpy

Let's quickly get a few definitions out of the way, and start. Start by collecting some objects together, first singly (scalar), then in a list (vector), then as a 'spreadsheet' (matrix), then as an array (3-dimensional, or higher dimensional).


### Scalars

If our collection of (numeric) objects coincidentally is only a single number, we call that a ***scalar***.
* ```python
scalar_1 = 45.2
```

* ```python
scalar_2 = 0
```

* ```python
scalar_3 = -12
```

### Vectors

A collection of scalars in a single row, or column, is very much like a `list` in regular Python. This collection we then call a ***vector***.
* ```python 
list_1 = [1, 2, 6, -2, 0]
```

* ```python 
list_2 = [0, 0, 0, 0, 0, 0, 0, 0]
```

* ```python 
list_3 = [254.2, 501, 368.4, 697, 476.5, 188.2, 525.6, 451, 514]
```


We say this collection has a single dimension: a single row of numbers, or a single column of numbers. If there coincidentally is 1 number in the collection, we simply call that a scalar. But in theory we can store as many numbers as we like in our vector.

Think, for example, the impeller speed of a batch reactor, measured every minute, during the duration of a batch. This 1-dimensional sequence is called a vector.

### Matrix

If we take several 1-dimensional vectors, but **each one of the same length**, and put them together, side-by-side then we get a ***matrix***. 

* ```python 
matrix_1 = [ [1, 2, 6, -2], [4, 3, 2, 1] ]   # has 2 rows and 4 columns```

* ```python 
matrix_2 = [ [0, 0, 0], [0, 0, 0], [0, 0, 0] ]   # has 3 rows and 3 columns```

* ```python 
matrix_3 = [ [9, 8, 7, 6], [5, 4, 4, 3] ]   # also has 2 rows and 4 columns```

You could crudely store, as we showed above, a matrix by using a list of lists, where the main list (the outside list) contains objects which themselves are lists. This is perfectly valid in Python: remember that a list can contain objects of any type, including other lists. But while this "list-of-lists" approach can store your data, it would not be great for calculations.

**Try this:** (the result is complely unintuitive for mathematical operations)
```python
matrix_1 + matrix_3
matrix_3 + 7
```
    
Another point to note is that a vector is simply a matrix, but where one of the dimensions is equal to 1: either 1 row, or 1 column. 

Matrices are widely used in engineering and data analysis. Often each row is an object, or a sample, or an observation. And each column represents some sort of value measured on that object or sample. For example:
<table>
  <tr>
    <th></th>
    <th>Measurement 1</th>
    <th>Measurement 2</th>
    <th>Measurement 3</th>
    <th>Measurement 4</th>
  </tr>
  <tr class="odd">
    <td>Sample 1</td>
    <td>5.5</td>
    <td>0.55</td>
    <td>-23.4</td>
    <td>561522.2</td>
  </tr>
  <tr class="odd">
    <td>Sample 2</td>
    <td>6.7</td>
    <td>0.44</td>
    <td>-22.2</td>
    <td>526616.4</td>
  </tr>
  <tr class="odd">
    <td>Sample 3</td>
    <td>4.9</td>
    <td>0.61</td>
    <td>-38.1</td>
    <td>612515.7</td>
  </tr>
</table>
This matrix would have 3 rows and 4 columns.

### Array

If we take several 2-dimensional matrices, but **each one with the same number of rows and columns**, and put them together, then we get a ***3-dimensional array***. 

A matrix was a list-of-lists. We can go up to a third dimension and make a list-of-lists-of-lists. 

Why stop there? We can go to higher and higher dimensions. We use a general names for such a collection of (numeric) objects: an ***array***. 

An array is an *n*-dimensional structure of numbers. You can therefore say:
* a vector is a 1-dimensional data structure
* a matrix is a 2-dimensional data structure
* an array is an *n*-dimensional data structure


<img src="Figures/data-layers-3d-structure.png" style="width: 400px; float: right"/> 

For example, a 3-dimensional array here shows data collected in a lab: we are performing the experiment several times (``N``, the layers - each layer is a matrix actually - that lies on top of each other). 

In each experiment we collect a matrix of data from several sensors. There are ``K`` sensors. We set the sensors to collect data on a regular interval, once every 3 seconds, for example, so that we end up with exactly the same number of samples per sensor, ``J`` values per sensor.


Storing the data like this is useful, because now you could perform calculations on all experiments over all time, for all sensors in array **X**.

*For example:* you can calculate the average in the direction of arrow ``J``, to reduce the *array* to a *matrix*. That matrix would be the average value of the sensor for the experiments. That reduced matrix would have ``N`` rows and ``K`` columns.

Engineering applications benefit from using *vectors*, or *matrices* or *arrays*: they are sequences of data all of the _same type_. Arrays behave a lot like lists in Python, except for the constraint that all elements have the same type. 


### Solution

In [16]:
import numpy as np

N = 5  # Number of experiments (layers)
K = 3  # Number of sensors
J = 4  # Number of samples per sensor

# Create a 3-dimensional array with random data
array_shape = (N, K, J)

data = np.random.rand(*array_shape)


print(data)

#calculate the average in the direction of axis J to reduce it to a 2-dimensional matrix
average_matrix = np.mean(data, axis=2)

print("Average Matrix: ")
print(average_matrix)


[[[0.2889145  0.31920529 0.57791693 0.52416216]
  [0.59256732 0.01041135 0.84708919 0.79002237]
  [0.22521246 0.36859006 0.87406418 0.26677268]]

 [[0.11910472 0.89419354 0.79028993 0.57041794]
  [0.56933131 0.84967065 0.92510405 0.11434499]
  [0.12441934 0.35050767 0.92837799 0.06364334]]

 [[0.06714919 0.43896664 0.56783726 0.14145717]
  [0.73008972 0.89669513 0.92914168 0.29748076]
  [0.08617117 0.5863018  0.93238892 0.87489855]]

 [[0.62303296 0.78068065 0.87372533 0.64341595]
  [0.7826683  0.84417499 0.1840746  0.76635281]
  [0.2257052  0.35623696 0.25803831 0.7455969 ]]

 [[0.96057861 0.63993256 0.01602597 0.6663381 ]
  [0.29351969 0.44896152 0.22562727 0.70687316]
  [0.13496542 0.11781081 0.12744473 0.75683563]]]
Average Matrix: 
[[0.42754972 0.56002256 0.43365984]
 [0.59350153 0.61461275 0.36673709]
 [0.30385257 0.71335182 0.61994011]
 [0.73021372 0.64431768 0.39639434]
 [0.57071881 0.41874541 0.28426415]]


## Section 4: Jupyter Presentation
Convert this Jupyter Notebook to reveal.js presentation

1. To convert a notebook into a reveal.js presentation, go to the View menu and set Cell Toolbar to Slideshow.
2. Organize the cells of your notebook into slides and sub-slides.
3. launch in a terminal window the following command: `jupyter nbconvert {NOTEBOOK_NAME}.ipynb to slide  --post serve`
4. open it on a new tab of your system default browser at
`http://localhost:8000/{NOTEBOOK_NAME}.slides.html/`




### Solution

In [ ]:
### Solution